# Inventory Analysis Capstone

Start by importing necessary Python libraries

In [23]:
import pandas as pd
import yfinance as yf
import numpy as np
import requests
import ast

## Data Acquisition - Inventory & COGS

Read in the dataset with the 500 companies first

In [80]:
companies = pd.read_csv('data/SP500.csv')
companies.head(5)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373

Collect Net Inventory from SEC filings for each company

In [ ]:
def fetch_sec_data(cik):
    headers = {'User-Agent' : 'marshalln@etown.edu', 'Host': 'data.sec.gov'}
    cik = str(cik).zfill(10)
    url = 'https://data.sec.gov/api/xbrl/companyfacts/CIK' + cik + '.json'
    response = requests.get(url,headers=headers)
    response.raise_for_status()
    try:
        inventory = response.json()['facts']['us-gaap']['InventoryNet']['units']['USD']
    except:
        inventory = None
    try:
        cogs = response.json()['facts']['us-gaap']['CostOfGoodsSold']['units']['USD']
    except: 
        cogs = None

    return (inventory, cogs)

In [26]:
data = pd.DataFrame(columns=['company', 'sector', 'inventory', 'cogs'])
for i in range(len(companies)):
    symbol = companies['Symbol'][i]
    sec_data = fetch_sec_data(companies['CIK'][i])
    if sec_data[0] and sec_data[1] is not None:
        data.loc[len(data)] = [symbol, companies['GICS Sector'][i], sec_data[0], sec_data[1]]
data.head()

,company,sector,inventory,cogs
0,AOS,Industrials,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
1,ABT,Health Care,"[{'end': '2007-12-31', 'val': 2951442000, 'acc...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."
2,ABBV,Health Care,"[{'end': '2012-12-31', 'val': 1091000000, 'acc...","[{'start': '2011-01-01', 'end': '2011-12-31', ..."
3,AMD,Information Technology,"[{'end': '2009-12-26', 'val': 567000000, 'accn...","[{'start': '2007-12-30', 'end': '2008-12-27', ..."
4,A,Health Care,"[{'end': '2008-10-31', 'val': 646000000, 'accn...","[{'start': '2006-11-01', 'end': '2007-10-31', ..."

Export to a csv file for easy use later

In [28]:
data.to_csv('data/financial_data_v2.csv', index=False)

## Data Exploration

In [104]:
financial_data = pd.read_csv('data/financial_data_v2.csv')

Observe the shape of the data

In [105]:
financial_data.shape

(151, 4)

Describe the data

In [106]:
financial_data.describe()

,company,sector,inventory,cogs
count,151,151,151,151
unique,151,10,151,151
top,AOS,Health Care,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
freq,1,31,1,1

Example of the data

In [107]:
financial_data.head(5)

,company,sector,inventory,cogs
0,AOS,Industrials,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
1,ABT,Health Care,"[{'end': '2007-12-31', 'val': 2951442000, 'acc...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."
2,ABBV,Health Care,"[{'end': '2012-12-31', 'val': 1091000000, 'acc...","[{'start': '2011-01-01', 'end': '2011-12-31', ..."
3,AMD,Information Technology,"[{'end': '2009-12-26', 'val': 567000000, 'accn...","[{'start': '2007-12-30', 'end': '2008-12-27', ..."
4,A,Health Care,"[{'end': '2008-10-31', 'val': 646000000, 'accn...","[{'start': '2006-11-01', 'end': '2007-10-31', ..."

Check for nulls

In [108]:
financial_data.isnull().sum()

company      0
sector       0
inventory    0
cogs         0
dtype: int64

Check for duplicates

In [109]:
financial_data.duplicated().value_counts()

False    151
Name: count, dtype: int64

## Data Cleaning

Remove duplicate & unnecessary information from inventory and cogs columns

In [110]:
def clean_inventory(data, metric): 
    data_list = ast.literal_eval(data)
    date = ''
    new_data = [] 
    for dict in data_list:
        if dict['end'] != date: 
            date = dict['end'] 
            temp = {'end' : date, metric : dict['val']}
            new_data.append(temp) 
    return new_data

In [111]:
financial_data['inventory'] = financial_data['inventory'].apply(clean_inventory, args=('inventory',))
financial_data['cogs'] = financial_data['cogs'].apply(clean_inventory, args=('cogs',))
financial_data.head()

,company,sector,inventory,cogs
0,AOS,Industrials,"[{'end': '2009-12-31', 'inventory': 215100000}...","[{'end': '2008-12-31', 'cogs': 1077200000}, {'..."
1,ABT,Health Care,"[{'end': '2007-12-31', 'inventory': 2951442000...","[{'end': '2007-12-31', 'cogs': 11422046000}, {..."
2,ABBV,Health Care,"[{'end': '2012-12-31', 'inventory': 1091000000...","[{'end': '2011-12-31', 'cogs': 4639000000}, {'..."
3,AMD,Information Technology,"[{'end': '2009-12-26', 'inventory': 567000000}...","[{'end': '2008-12-27', 'cogs': 3488000000}, {'..."
4,A,Health Care,"[{'end': '2008-10-31', 'inventory': 646000000}...","[{'end': '2007-10-31', 'cogs': 1928000000}, {'..."

Create separate date and inventory/cogs columns

In [112]:
def split_data(row):
    df = pd.DataFrame(columns=['company','sector', 'inventory', 'cogs', 'date'])
    for inventory, cogs in zip(row['inventory'], row['cogs']):
        df.loc[len(df)] = [row['company'], row['sector'], inventory['inventory'], cogs['cogs'], pd.to_datetime(inventory['end'])]
    return df

In [113]:
clean_financial_data = pd.DataFrame(columns = ['company', 'sector', 'inventory', 'cogs', 'date'])
for i in range(len(financial_data)):
    clean_financial_data = pd.concat([clean_financial_data, split_data(financial_data.iloc[i])], ignore_index=True)

Briefly inspect the cleaned data

In [114]:
print(len(clean_financial_data))

4717

In [115]:
clean_financial_data.tail()

     company       sector   inventory        cogs                 date
4712     ZBH  Health Care  1962100000  1040600000  2016-06-30 00:00:00
4713     ZBH  Health Care  2070000000  1541500000  2016-09-30 00:00:00
4714     ZBH  Health Care  1959400000  2132900000  2016-12-31 00:00:00
4715     ZBH  Health Care  1977000000   575800000  2017-03-31 00:00:00
4716     ZBH  Health Care  2023900000  1159500000  2017-06-30 00:00:00

Change date column to YYYY-MM-DD

In [116]:
clean_financial_data['date'] =  pd.to_datetime(clean_financial_data['date']).dt.date

Change ticker for Yahoo Finance API

In [119]:
clean_financial_data['company'] = clean_financial_data['company'].apply(lambda x: 'BF-B' if x == 'BF.B' else x)

Remove company with ticker K because it is delisted from Yahoo Finance API

In [120]:
clean_financial_data = clean_financial_data[clean_financial_data['company'] != 'K']

## Data Aquisition - Stock Prices

Use the current data to grab stock prices

In [42]:
def get_stocks(company, rows):
    ticker = yf.Ticker(company)
    history = ticker.history(period='max') #(start=rows['date'].min(), end = rows['date'].max())
    history['date'] = history.index
    rows['date'] = pd.to_datetime(rows['date']).dt.normalize().dt.tz_localize('America/New_York').astype('datetime64[s, America/New_York]')
    history.rename(columns={'Close': 'price'}, inplace=True)
    rows = rows.sort_values('date')
    history = history.sort_values('date')
    try:
        return pd.merge_asof(rows, history[['date', 'price']], on='date')
    except:
        return None

In [59]:
stocks_data = pd.DataFrame(columns=['company', 'date', 'price'])

for company, rows in clean_financial_data.groupby('company'):
    df = get_stocks(company, rows)
    if df is not None:
        stocks_data = pd.concat([stocks_data, df[['company', 'date', 'price']]], ignore_index=True)

## Data Exploration - Stocks

Check shape of stock data

In [60]:
stocks_data.shape

(4676, 3)

Check for null values

In [61]:
stocks_data.isnull().sum()

company     0
date        0
price      44
dtype: int64

Observe the data

In [62]:
stocks_data.head()

  company                       date      price
0       A  2008-10-31 00:00:00-04:00  14.044913
1       A  2009-07-31 00:00:00-04:00  14.696836
2       A  2009-10-31 00:00:00-04:00  15.658907
3       A  2010-01-31 00:00:00-05:00  17.741274
4       A  2010-04-30 00:00:00-04:00  22.950361

In [63]:
stocks_data.tail()

     company                       date       price
4671    ZBRA  2018-01-01 00:00:00-05:00  103.800003
4672    ZBRA  2018-03-31 00:00:00-04:00  139.190002
4673    ZBRA  2018-06-30 00:00:00-04:00      143.25
4674    ZBRA  2018-09-29 00:00:00-04:00  176.830002
4675    ZBRA  2018-12-31 00:00:00-05:00  159.229996

## Data Cleaning - Stocks

In [192]:
null_df = stocks_data[stocks_data['price'].isnull()]
null_df.head(10)

  company                       date price
0    ABBV  2012-12-31 00:00:00-05:00   NaN
0    ANET  2013-12-31 00:00:00-05:00   NaN
0    CARR  2019-12-31 00:00:00-05:00   NaN
0     CDW  2010-12-31 00:00:00-05:00   NaN
1     CDW  2011-06-30 00:00:00-04:00   NaN
2     CDW  2011-09-30 00:00:00-04:00   NaN
3     CDW  2011-12-31 00:00:00-05:00   NaN
4     CDW  2012-03-31 00:00:00-04:00   NaN
5     CDW  2012-06-30 00:00:00-04:00   NaN
6     CDW  2012-09-30 00:00:00-04:00   NaN

Only 44 rows have null price so just them remove from the dataframe

In [193]:
stocks_data = stocks_data[stocks_data['price'].isnull() == False]

Change date column to YYYY-MM-DD format

In [64]:
stocks_data['date'] = pd.to_datetime(stocks_data['date']).dt.date

Save stock data to csv for later use

In [195]:
stocks_data.to_csv('data/stock_data.csv', index=False)

## Data Cleaning - Companies

Add company names to data

In [ ]:
def add_company_name(x):
    if x == 'BF-B':
        return 'Brown–Forman'
    else:
        return companies[companies['Symbol'] == x]['Security'].iloc[0]

clean_financial_data['company_name'] = clean_financial_data['company'].apply(add_company_name)

In [103]:
clean_financial_data[clean_financial_data['company_name'] == 'BF-B']

Empty DataFrame
Columns: [company, sector, inventory, cogs, date, company_name]
Index: []

## Export Data to Database

Create an engine and start up docker

In [91]:
from sqlalchemy import create_engine
PG_URL = 'postgresql+psycopg2://postgres:postgres@localhost:5432/postgres'
engine = create_engine(PG_URL)
print('Database:', PG_URL)

Database: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres

Export the company data to create a company table

In [97]:
clean_financial_data[['company', 'company_name', 'sector']].drop_duplicates().to_sql('companies', engine, if_exists='replace', index=False)

150

Export the financial data to create a financial data table

In [73]:
clean_financial_data[['company', 'inventory', 'cogs', 'date']].to_sql('financial_data', engine, if_exists='replace', index=False)

676

Export the stock data to create a stock data table

In [67]:
stocks_data.to_sql('stock_data', engine, if_exists='replace', index=False)

676

Close the engine

In [74]:
engine.dispose()

Verify that the tables were created

In [75]:
from sqlalchemy import text

with engine.connect() as connection:
    print('company table:', connection.execute(text('SELECT COUNT(*) FROM companies')).fetchall()[0][0], 'rows')
    print('financial data table:', connection.execute(text('SELECT COUNT(*) FROM financial_data')).fetchall()[0][0], 'rows')
    print('stock data table:', connection.execute(text('SELECT COUNT(*) FROM stock_data')).fetchall()[0][0], 'rows')

company table: 151 rows
financial data table: 4676 rows
stock data table: 4676 rows

## The End