# Inventory Analysis Capstone

Start by importing necessary Python libraries

In [4]:
import pandas as pd
import yfinance as yf
import requests
import ast

## Data Acquisition - Inventory & COGS

Read in the dataset with the 500 companies first

In [19]:
companies = pd.read_csv('data/SP500.csv')
companies.head(5)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373

Collect Net Inventory from SEC filings for each company

In [19]:
def fetch_sec_data(cik):
    headers = {'User-Agent' : 'marshalln@etown.edu', 'Host': 'data.sec.gov'}
    cik = str(cik).zfill(10)
    url = 'https://data.sec.gov/api/xbrl/companyfacts/CIK' + cik + '.json'
    response = requests.get(url,headers=headers)
    response.raise_for_status()
    try:
        inventory = response.json()['facts']['us-gaap']['InventoryNet']['units']['USD']
    except:
         return None
    try:
        cogs = response.json()['facts']['us-gaap']['CostOfGoodsSold']['units']['USD']
    except: 
        return None
    try:
        sales = response.json()['facts']['us-gaap']['SalesRevenueGoodsNet']['units']['USD']
    except: 
        return None
    return (inventory, cogs, sales)

In [20]:
data = pd.DataFrame(columns=['company', 'sector', 'inventory', 'cogs', 'sales'])
for i in range(len(companies)):
    symbol = companies['Symbol'][i]
    sec_data = fetch_sec_data(companies['CIK'][i])
    if sec_data is not None:
        data.loc[len(data)] = [symbol, companies['GICS Sector'][i], sec_data[0], sec_data[1], sec_data[2]]
data.head()

,company,sector,inventory,cogs,sales
0,AOS,Industrials,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
1,AMD,Information Technology,"[{'end': '2009-12-26', 'val': 567000000, 'accn...","[{'start': '2007-12-30', 'end': '2008-12-27', ...","[{'start': '2007-12-30', 'end': '2008-12-27', ..."
2,A,Health Care,"[{'end': '2008-10-31', 'val': 646000000, 'accn...","[{'start': '2006-11-01', 'end': '2007-10-31', ...","[{'start': '2006-11-01', 'end': '2007-10-31', ..."
3,ALGN,Health Care,"[{'end': '2009-12-31', 'val': 2046000, 'accn':...","[{'start': '2008-01-01', 'end': '2008-12-31', ...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
4,AMGN,Health Care,"[{'end': '2008-12-31', 'val': 2075000000, 'acc...","[{'start': '2011-01-01', 'end': '2011-12-31', ...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."

Export to a csv file for easy use later

In [22]:
data.to_csv('data/financial_data_v3.csv', index=False)

## Data Exploration

In [5]:
financial_data = pd.read_csv('data/financial_data_v3.csv')

Observe the shape of the data

In [6]:
financial_data.shape

(109, 5)

Describe the data

In [27]:
financial_data.describe()

,company,sector,inventory,cogs,sales
count,109,109,109,109,109
unique,109,9,109,109,109
top,AOS,Health Care,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
freq,1,26,1,1,1

Example of the data

In [28]:
financial_data.head()

,company,sector,inventory,cogs,sales
0,AOS,Industrials,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
1,AMD,Information Technology,"[{'end': '2009-12-26', 'val': 567000000, 'accn...","[{'start': '2007-12-30', 'end': '2008-12-27', ...","[{'start': '2007-12-30', 'end': '2008-12-27', ..."
2,A,Health Care,"[{'end': '2008-10-31', 'val': 646000000, 'accn...","[{'start': '2006-11-01', 'end': '2007-10-31', ...","[{'start': '2006-11-01', 'end': '2007-10-31', ..."
3,ALGN,Health Care,"[{'end': '2009-12-31', 'val': 2046000, 'accn':...","[{'start': '2008-01-01', 'end': '2008-12-31', ...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
4,AMGN,Health Care,"[{'end': '2008-12-31', 'val': 2075000000, 'acc...","[{'start': '2011-01-01', 'end': '2011-12-31', ...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."

Check for nulls

In [29]:
financial_data.isnull().sum()

company      0
sector       0
inventory    0
cogs         0
sales        0
dtype: int64

Check for duplicates

In [30]:
financial_data.duplicated().value_counts()

False    109
Name: count, dtype: int64

## Data Cleaning

Remove duplicate & unnecessary information from inventory and cogs columns

In [7]:
def clean_inventory(data, metric): 
    data_list = ast.literal_eval(data)
    date = ''
    new_data = [] 
    for dict in data_list:
        if dict['end'] != date: 
            date = dict['end'] 
            temp = {'end' : date, metric : dict['val']}
            new_data.append(temp) 
    return new_data

In [8]:
financial_data['inventory'] = financial_data['inventory'].apply(clean_inventory, args=('inventory',))
financial_data['cogs'] = financial_data['cogs'].apply(clean_inventory, args=('cogs',))
financial_data['sales'] = financial_data['sales'].apply(clean_inventory, args=('sales',))
financial_data.head()

,company,sector,inventory,cogs,sales
0,AOS,Industrials,"[{'end': '2009-12-31', 'inventory': 215100000}...","[{'end': '2008-12-31', 'cogs': 1077200000}, {'...","[{'end': '2008-12-31', 'sales': 1451300000}, {..."
1,AMD,Information Technology,"[{'end': '2009-12-26', 'inventory': 567000000}...","[{'end': '2008-12-27', 'cogs': 3488000000}, {'...","[{'end': '2008-12-27', 'sales': 5808000000}, {..."
2,A,Health Care,"[{'end': '2008-10-31', 'inventory': 646000000}...","[{'end': '2007-10-31', 'cogs': 1928000000}, {'...","[{'end': '2007-10-31', 'sales': 4505000000}, {..."
3,ALGN,Health Care,"[{'end': '2009-12-31', 'inventory': 2046000}, ...","[{'end': '2008-12-31', 'cogs': 69536000}, {'en...","[{'end': '2008-12-31', 'sales': 285798000}, {'..."
4,AMGN,Health Care,"[{'end': '2008-12-31', 'inventory': 2075000000...","[{'end': '2011-12-31', 'cogs': 2708000000}, {'...","[{'end': '2007-12-31', 'sales': 14311000000}, ..."

Create separate date and inventory/cogs columns

In [9]:
def split_data(row):
    df = pd.DataFrame(columns=['company','sector', 'inventory', 'cogs', 'sales', 'date'])
    for inventory, cogs, sales in zip(row['inventory'], row['cogs'], row['sales']):
        df.loc[len(df)] = [row['company'], row['sector'], inventory['inventory'], cogs['cogs'], sales['sales'], pd.to_datetime(inventory['end'])]
    return df

In [10]:
clean_financial_data = pd.DataFrame(columns = ['company', 'sector', 'inventory', 'cogs', 'sales', 'date'])
for i in range(len(financial_data)):
    clean_financial_data = pd.concat([clean_financial_data, split_data(financial_data.iloc[i])], ignore_index=True)

Briefly inspect the cleaned data

In [11]:
print(len(clean_financial_data))

3262

In [12]:
clean_financial_data.tail()

,company,sector,inventory,cogs,sales,date
3257,ZBH,Health Care,1962100000,1040600000,1977300000,2016-06-30 00:00:00
3258,ZBH,Health Care,2070000000,1541500000,3931700000,2016-09-30 00:00:00
3259,ZBH,Health Care,1959400000,2132900000,5749800000,2016-12-31 00:00:00
3260,ZBH,Health Care,1977000000,575800000,7824100000,2017-03-31 00:00:00
3261,ZBH,Health Care,2023900000,1159500000,2017600000,2017-06-30 00:00:00

Change date column to YYYY-MM-DD

In [13]:
clean_financial_data['date'] =  pd.to_datetime(clean_financial_data['date']).dt.date

Change ticker for Yahoo Finance API

In [14]:
clean_financial_data['company'] = clean_financial_data['company'].apply(lambda x: 'BF-B' if x == 'BF.B' else x)

Remove company with ticker K because it is delisted from Yahoo Finance API

In [15]:
clean_financial_data = clean_financial_data[clean_financial_data['company'] != 'K']

Create Average Inventory Column (Avg Inventory = (Beginning Inventory + Ending Inventory)/2)

In [16]:
clean_financial_data['avg_inventory'] = clean_financial_data['inventory'].shift(1)

clean_financial_data['avg_inventory'] = (clean_financial_data['avg_inventory'] + clean_financial_data['inventory']) / 2

In [17]:
clean_financial_data.head()

,company,sector,inventory,cogs,sales,date,avg_inventory
0,AOS,Industrials,215100000,1077200000,1451300000,2009-12-31,NaN
1,AOS,Industrials,257100000,756500000,980400000,2010-06-30,236100000.0
2,AOS,Industrials,268600000,1119500000,1481900000,2010-09-30,262850000.0
3,AOS,Industrials,146800000,980100000,1375000000,2010-12-31,207700000.0
4,AOS,Industrials,160800000,258400000,366700000,2011-03-31,153800000.0

## Data Aquisition - Stock Prices

Use the current data to grab stock prices

In [45]:
def get_stocks(company, rows):
    ticker = yf.Ticker(company)
    history = ticker.history(period='max') #(start=rows['date'].min(), end = rows['date'].max())
    history['date'] = history.index
    rows['date'] = pd.to_datetime(rows['date']).dt.normalize().dt.tz_localize('America/New_York').astype('datetime64[s, America/New_York]')
    history.rename(columns={'Close': 'price'}, inplace=True)
    rows = rows.sort_values('date')
    history = history.sort_values('date')
    try:
        return pd.merge_asof(rows, history[['date', 'price']], on='date')
    except:
        return None

In [65]:
stocks_data = pd.DataFrame(columns=['company', 'date', 'price'])

for company, rows in clean_financial_data.groupby('company'):
    df = get_stocks(company, rows)
    if df is not None:
        stocks_data = pd.concat([stocks_data, df[['company', 'date', 'price']]], ignore_index=True)

## Data Exploration - Stocks

Check shape of stock data

In [66]:
stocks_data.shape

(3221, 3)

Check for null values

In [67]:
stocks_data.isnull().sum()

company     0
date        0
price      40
dtype: int64

Observe the data

In [68]:
stocks_data.head()

  company                       date      price
0       A  2008-10-31 00:00:00-04:00  14.044909
1       A  2009-07-31 00:00:00-04:00  14.696833
2       A  2009-10-31 00:00:00-04:00  15.658907
3       A  2010-01-31 00:00:00-05:00  17.741278
4       A  2010-04-30 00:00:00-04:00  22.950357

In [69]:
stocks_data.tail()

     company                       date       price
3216    ZBRA  2018-01-01 00:00:00-05:00  103.800003
3217    ZBRA  2018-03-31 00:00:00-04:00  139.190002
3218    ZBRA  2018-06-30 00:00:00-04:00      143.25
3219    ZBRA  2018-09-29 00:00:00-04:00  176.830002
3220    ZBRA  2018-12-31 00:00:00-05:00  159.229996

## Data Cleaning - Stocks

In [70]:
null_df = stocks_data[stocks_data['price'].isnull()]
null_df.head(10)

     company                       date price
116     ANET  2013-12-31 00:00:00-05:00   NaN
731     DELL  2016-01-29 00:00:00-05:00   NaN
732     DELL  2016-04-29 00:00:00-04:00   NaN
733     DELL  2016-07-29 00:00:00-04:00   NaN
1249     HII  2010-12-31 00:00:00-05:00   NaN
1336     HPE  2014-10-31 00:00:00-04:00   NaN
1405     HWM  2008-12-31 00:00:00-05:00   NaN
1406     HWM  2009-06-30 00:00:00-04:00   NaN
1407     HWM  2009-09-30 00:00:00-04:00   NaN
1408     HWM  2009-12-31 00:00:00-05:00   NaN

Only 40 rows have null price so just them remove from both dataframes

In [72]:
stocks_data = stocks_data[stocks_data['price'].isnull() == False]

In [73]:
len(clean_financial_data)

3221

Change date column to YYYY-MM-DD format

In [74]:
stocks_data['date'] = pd.to_datetime(stocks_data['date']).dt.date

Create a stock returns column (stock returns = (ending stock price - initial stock price)/initial stock price * 100)

In [75]:
stocks_data['return'] = stocks_data['price'].shift(1)

stocks_data['return'] = (stocks_data['return'] - stocks_data['price']) / stocks_data['price'] * -100

In [76]:
stocks_data.head()

  company        date      price     return
0       A  2008-10-31  14.044909        NaN
1       A  2009-07-31  14.696833   4.435807
2       A  2009-10-31  15.658907   6.143943
3       A  2010-01-31  17.741278  11.737434
4       A  2010-04-30  22.950357  22.697162

Save stock data to csv for later use

In [78]:
stocks_data.to_csv('data/stock_data.csv', index=False)

## Data Cleaning - Companies

Add company names to data

In [20]:
def add_company_name(x):
    if x == 'BF-B':
        return 'Brown–Forman'
    else:
        return companies[companies['Symbol'] == x]['Security'].iloc[0]

clean_financial_data['company_name'] = clean_financial_data['company'].apply(add_company_name)

## Export Data to Database

Create an engine and start up docker

In [1]:
from sqlalchemy import create_engine
PG_URL = 'postgresql+psycopg2://postgres:postgres@localhost:5432/postgres'
engine = create_engine(PG_URL)
print('Database:', PG_URL)

Database: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres

Export the company data to create a company table

In [21]:
clean_financial_data[['company_name', 'sector']].drop_duplicates().to_sql('companies', engine, if_exists='replace', index=False)

108

Export the financial data to create a financial data table

In [22]:
clean_financial_data[['company_name', 'date', 'inventory', 'avg_inventory', 'cogs', 'sales']].to_sql('financial_data', engine, if_exists='replace', index=False)

221

Export the stock data to create a stock data table

In [83]:
stocks_data.to_sql('stock_data', engine, if_exists='replace', index=False)

181

Close the engine

In [23]:
engine.dispose()

Verify that the tables were created

In [24]:
from sqlalchemy import text

with engine.connect() as connection:
    print('company table:', connection.execute(text('SELECT COUNT(*) FROM companies')).fetchall()[0][0], 'rows')
    print('financial data table:', connection.execute(text('SELECT COUNT(*) FROM financial_data')).fetchall()[0][0], 'rows')
    print('stock data table:', connection.execute(text('SELECT COUNT(*) FROM stock_data')).fetchall()[0][0], 'rows')

company table: 108 rows
financial data table: 3221 rows
stock data table: 3181 rows

## The End