# Inventory Analysis Capstone

Start by importing necessary Python libraries

In [ ]:
import pandas as pd
import yfinance as yf
import numpy as np
import requests
import ast

## Data Acquisition - Inventory & COGS

Read in the dataset with the 500 companies first

In [2]:
companies = pd.read_csv('data/SP500.csv')
companies.head(5)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373

Collect Net Inventory from SEC filings for each company

In [3]:
def fetch_sec_data(cik):
    headers = {'User-Agent' : 'marshalln@etown.edu', 'Host': 'data.sec.gov'}
    cik = str(cik).zfill(10)
    url = 'https://data.sec.gov/api/xbrl/companyfacts/CIK' + cik + '.json'
    response = requests.get(url,headers=headers)
    response.raise_for_status()
    try:
        inventory = response.json()['facts']['us-gaap']['InventoryNet']['units']['USD']
    except:
        inventory = None
    try:
        cogs = response.json()['facts']['us-gaap']['CostOfGoodsSold']['units']['USD']
    except: 
        try:
            cogs = response.json()['facts']['us-gaap']['CostOfGoodsAndServicesSold']['units']['USD']
        except:
            try:
                cogs = response.json()['facts']['us-gaap']['CostOfRevenue']['units']['USD']
            except:
                try:
                    cogs = response.json()['facts']['us-gaap']['CostOfSales']['units']['USD']
                except:
                    cogs = None

    return (inventory, cogs)

In [6]:
data = pd.DataFrame(columns=['company', 'industry', 'inventory', 'cogs'])
for i in range(len(companies)):
    symbol = companies['Symbol'][i]
    sec_data = fetch_sec_data(companies['CIK'][i])
    if sec_data[0] and sec_data[1] is not None:
        data.loc[len(data)] = [symbol, companies['GICS Sub-Industry'][i], sec_data[0], sec_data[1]]
data.head()

,company,industry,inventory,cogs
0,MMM,Industrial Conglomerates,"[{'end': '2008-12-31', 'val': 3013000000, 'acc...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."
1,AOS,Building Products,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
2,ABT,Health Care Equipment,"[{'end': '2007-12-31', 'val': 2951442000, 'acc...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."
3,ABBV,Biotechnology,"[{'end': '2012-12-31', 'val': 1091000000, 'acc...","[{'start': '2011-01-01', 'end': '2011-12-31', ..."
4,AMD,Semiconductors,"[{'end': '2009-12-26', 'val': 567000000, 'accn...","[{'start': '2007-12-30', 'end': '2008-12-27', ..."

Export to a csv file for easy use later

In [7]:
data.to_csv('data/financial_data.csv', index=False)

## Data Exploration

In [2]:
financial_data = pd.read_csv('data/financial_data.csv')

Observe the shape of the data

In [9]:
print(financial_data.shape)

(281, 4)

Describe the data

In [10]:
print(financial_data.describe())

       company               industry  \
count      281                    281
unique     281                     87
top        MMM  Health Care Equipment
freq         1                     16

                                                inventory  \
count                                                 281
unique                                                280
top     [{'end': '2015-12-31', 'val': 491000000, 'accn...
freq                                                    2

                                                     cogs
count                                                 281
unique                                                280
top     [{'start': '2013-01-01', 'end': '2013-12-31', ...
freq                                                    2

Example of the data

In [11]:
financial_data.head(5)

,company,industry,inventory,cogs
0,MMM,Industrial Conglomerates,"[{'end': '2008-12-31', 'val': 3013000000, 'acc...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."
1,AOS,Building Products,"[{'end': '2009-12-31', 'val': 215100000, 'accn...","[{'start': '2008-01-01', 'end': '2008-12-31', ..."
2,ABT,Health Care Equipment,"[{'end': '2007-12-31', 'val': 2951442000, 'acc...","[{'start': '2007-01-01', 'end': '2007-12-31', ..."
3,ABBV,Biotechnology,"[{'end': '2012-12-31', 'val': 1091000000, 'acc...","[{'start': '2011-01-01', 'end': '2011-12-31', ..."
4,AMD,Semiconductors,"[{'end': '2009-12-26', 'val': 567000000, 'accn...","[{'start': '2007-12-30', 'end': '2008-12-27', ..."

Check for nulls

In [12]:
financial_data.isnull().sum()

company      0
industry     0
inventory    0
cogs         0
dtype: int64

Check for duplicates

In [13]:
financial_data.duplicated().value_counts()

False    281
Name: count, dtype: int64

## Data Cleaning

Remove duplicate & unnecessary information from inventory and cogs columns

In [3]:
def clean_inventory(data, metric): 
    data_list = ast.literal_eval(data)
    date = ''
    new_data = [] 
    for dict in data_list:
        if dict['end'] != date: 
            date = dict['end'] 
            temp = {'end' : date, metric : dict['val']}
            new_data.append(temp) 
    return new_data

In [4]:
financial_data['inventory'] = financial_data['inventory'].apply(clean_inventory, args=('inventory',))
financial_data['cogs'] = financial_data['cogs'].apply(clean_inventory, args=('cogs',))
financial_data.head(5)

,company,industry,inventory,cogs
0,MMM,Industrial Conglomerates,"[{'end': '2008-12-31', 'inventory': 3013000000...","[{'end': '2007-12-31', 'cogs': 12735000000}, {..."
1,AOS,Building Products,"[{'end': '2009-12-31', 'inventory': 215100000}...","[{'end': '2008-12-31', 'cogs': 1077200000}, {'..."
2,ABT,Health Care Equipment,"[{'end': '2007-12-31', 'inventory': 2951442000...","[{'end': '2007-12-31', 'cogs': 11422046000}, {..."
3,ABBV,Biotechnology,"[{'end': '2012-12-31', 'inventory': 1091000000...","[{'end': '2011-12-31', 'cogs': 4639000000}, {'..."
4,AMD,Semiconductors,"[{'end': '2009-12-26', 'inventory': 567000000}...","[{'end': '2008-12-27', 'cogs': 3488000000}, {'..."

Create separate date and inventory/cogs columns

In [6]:
def split_data(row):
    df = pd.DataFrame(columns=['company','industry', 'inventory', 'cogs', 'date'])
    for inventory, cogs in zip(row['inventory'], row['cogs']):
        df.loc[len(df)] = [row['company'], row['industry'], inventory['inventory'], cogs['cogs'], pd.to_datetime(inventory['end'])]
    return df

In [7]:
clean_financial_data = pd.DataFrame(columns = ['company', 'industry', 'inventory', 'cogs', 'date'])
for i in range(len(financial_data)):
    clean_financial_data = pd.concat([clean_financial_data, split_data(financial_data.iloc[i])], ignore_index=True)

Correct ticker format (useful for next step)

In [8]:
clean_financial_data['company'] = clean_financial_data['company'].apply(lambda x: 'BF-B' if x == 'BF.B' else x)

Briefly inspect the cleaned data

In [7]:
print(len(clean_financial_data))

10598

In [8]:
clean_financial_data.tail()

      company         industry   inventory        cogs                 date
10593     ZTS  Pharmaceuticals  2306000000  2561000000  2024-12-31 00:00:00
10594     ZTS  Pharmaceuticals  2365000000   643000000  2025-03-31 00:00:00
10595     ZTS  Pharmaceuticals  2439000000  1311000000  2025-06-30 00:00:00
10596     ZTS  Pharmaceuticals  2465000000  2012000000  2025-09-30 00:00:00
10597     ZTS  Pharmaceuticals  2430000000  2719000000  2025-12-31 00:00:00

## Data Aquisition - Stock Prices

Use the current data to grab stock data

In [9]:
def get_stocks(company, rows):
    ticker = yf.Ticker(company)
    history = ticker.history(period='max') #(start=rows['date'].min(), end = rows['date'].max())
    history['date'] = history.index
    rows['date'] = pd.to_datetime(rows['date']).dt.normalize().dt.tz_localize('America/New_York').astype('datetime64[s, America/New_York]')
    history.rename(columns={'Close': 'price'}, inplace=True)
    rows = rows.sort_values('date')
    history = history.sort_values('date')
    try:
        return pd.merge_asof(rows, history[['date', 'price']], on='date')
    except:
        return None

In [ ]:
stocks_data = pd.DataFrame(columns=['company', 'date', 'price'])

for company, rows in clean_financial_data.groupby('company'):
    df = get_stocks(company, rows)
    if df is not None:
        stocks_data = pd.concat([stocks_data, df[['company', 'date', 'price']]], ignore_index=True)

## Data Exploration - Stocks

Check shape of stock data

In [183]:
stocks_data.shape

(10557, 3)

Check for null values

In [184]:
stocks_data.isnull().sum()

company     0
date        0
price      76
dtype: int64

Observe the data

In [185]:
stocks_data.head()

  company                       date      price
0       A  2008-10-31 00:00:00-04:00  14.044909
1       A  2009-07-31 00:00:00-04:00  14.696841
2       A  2009-10-31 00:00:00-04:00  15.658903
3       A  2010-01-31 00:00:00-05:00  17.741278
4       A  2010-04-30 00:00:00-04:00  22.950356

In [186]:
stocks_data.tail()

   company                       date       price
48     ZTS  2024-12-31 00:00:00-05:00  160.109543
49     ZTS  2025-03-31 00:00:00-04:00   162.28891
50     ZTS  2025-06-30 00:00:00-04:00  154.232361
51     ZTS  2025-09-30 00:00:00-04:00  145.192337
52     ZTS  2025-12-31 00:00:00-05:00  125.285027

## Data Cleaning - Stocks

In [192]:
null_df = stocks_data[stocks_data['price'].isnull()]
null_df.head(10)

  company                       date price
0    ABBV  2012-12-31 00:00:00-05:00   NaN
0    ANET  2013-12-31 00:00:00-05:00   NaN
0    CARR  2019-12-31 00:00:00-05:00   NaN
0     CDW  2010-12-31 00:00:00-05:00   NaN
1     CDW  2011-06-30 00:00:00-04:00   NaN
2     CDW  2011-09-30 00:00:00-04:00   NaN
3     CDW  2011-12-31 00:00:00-05:00   NaN
4     CDW  2012-03-31 00:00:00-04:00   NaN
5     CDW  2012-06-30 00:00:00-04:00   NaN
6     CDW  2012-09-30 00:00:00-04:00   NaN

Only 76 rows have null price so just them remove from the dataframe

In [193]:
stocks_data = stocks_data[stocks_data['price'].isnull() == False]

In [194]:
len(stocks_data)

10481

Save stock data to csv for later use

In [195]:
stocks_data.to_csv('data/stock_data.csv', index=False)

### Export Data to Database

Create an engine and start up docker

In [12]:
from sqlalchemy import create_engine
PG_URL = 'postgresql+psycopg2://postgres:postgres@localhost:5432/postgres'
engine = create_engine(PG_URL)
print('Database:', PG_URL)

Database: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres

Export the company data to create a company table

In [216]:
clean_financial_data[['company', 'industry']].drop_duplicates().to_sql('companies', engine, if_exists='replace', index=False)

281

Export the financial data to create a financial data table

In [13]:
clean_financial_data[['company', 'inventory', 'cogs', 'date']].to_sql('financial_data', engine, if_exists='replace', index=False)

598

Export the stock data to create a stock data table

In [209]:
stocks_data.to_sql('stock_data', engine, if_exists='replace', index=False)

481

Close the engine

In [14]:
engine.dispose()

Verify that the tables were created

In [15]:
from sqlalchemy import text

with engine.connect() as connection:
    print('company table:', connection.execute(text('SELECT COUNT(*) FROM companies')).fetchall()[0][0], 'rows')
    print('financial data table:', connection.execute(text('SELECT COUNT(*) FROM financial_data')).fetchall()[0][0], 'rows')
    print('stock data table:', connection.execute(text('SELECT COUNT(*) FROM stock_data')).fetchall()[0][0], 'rows')

company table: 281 rows
financial data table: 10598 rows
stock data table: 10481 rows

## The End